name: _
publish_to: none
environment:
  sdk: ^3.9.2
workspace:
  - packages/appletheia
  - packages/appletheia_application
  - packages/appletheia_infrastructure
  - packages/appletheia_presentation
  - packages/appletheia_monad
dev_dependencies:
  melos: ^7.2.0

melos:
  repository: https://github.com/Lethephobia/flutter_appletheia
  scripts:
    generate:
      run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build
